
services:
  mongodb:
    image: mongo:6.0
    container_name: nexus_release_mongodb
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
    command: ["-js"]
    networks:
      - backend
  
  gateway:
    build: ../../gateway/api-gateway
    container_name: gateway
    networks:
      - frontend
      - backend
    environment:
      SECRETJWTKEY: mysecretkey
      NATSURL: nats://nats:4222
    ports:
      - "3000:3000"

  auth_service:
    build: ../../services/auth-service
    container_name: auth_service
    networks:
      - backend
    environment:
      SECRETJWTKEY: mysecretkey
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb

  user_service:
    build: ../../services/user-service
    container_name: user_service
    networks:
      - backend
    environment:
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
      - auth_service

  universe_service:
    build: ../../services/univer-service
    container_name: universe_service
    networks:
      - backend
    environment:
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
      - auth_service

  project_service:
    build: ../../services/project-service
    container_name: project_service
    networks:
      - backend
    environment:
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
      - auth_service

networks:
  frontend:
  backend:
