
services:
  mongodb:
    image: mongo:6.0
    container_name: nexus_release_mongodb
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
    command: ["-js"]
    networks:
      - backend

  gateway:
    container_name: gateway
    image: kevin24karat/gateway:0.0.1
    networks:
      - frontend
      - backend
    environment:
      SECRETJWTKEY: mysecretkey
      NATSURL: nats://nats:4222
    ports:
      - 3000:3000

  auth_service:
    container_name: auth_service
    image: kevin24karat/auth_service:0.0.1
    networks:
      - backend
    environment:
      SECRETJWTKEY: mysecretkey
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb

  user_service:
    container_name: user_service
    image: kevin24karat/user_service:0.0.1
    networks:
      - backend
    environment:
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
      - auth_service

  universe_service:
    container_name: universe_service
    image: kevin24karat/universe_service:0.0.1
    networks:
      - backend
    environment:
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
      - auth_service

  project_service:
    container_name: project_service
    image: kevin24karat/project_service:0.0.1
    networks:
      - backend
    environment:
      NATSURL: nats://nats:4222
      MONGOURL: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
      - auth_service

networks:
  frontend:
  backend:
